// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzntkumzvqqjjavrmuqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56bnRrdW16dnFxamphdnJtdXFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNDY5NTksImV4cCI6MjA2OTkyMjk1OX0.nXtS2ZwLhAwJJgFQh5pjQM8SK_G7ahsh-RyUOJ6Sa6c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});